apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-samples
  name: k8s-samples
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-samples
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-samples
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
         limits:
          cpu: "1000m"
          memory: "1G"
         requests:
          cpu: "500m"
          memory: "512Mi"
status: {}
