apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-samples
  name: k8s-samples
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: k8s-samples
  type: LoadBalancer
status:
  loadBalancer: {}
